name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: create-directory
      uses: nekiro/ssh-job@main
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.KEY }}
        user: ${{ secrets.USER }}
        command: |
          ls -l

        # cd /home/cloudpanel/htdocs/clean-dev.dev-laravel.co
        # git pull
        # composer install
        # echo "yes" | php8.1 artisan migrate
        # php8.1 artisan config:cache
        # php8.1 artisan view:cache
        # php8.1 artisan route:cache
        # php8.1 artisan config:cache






