name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run sshpass commands
      uses: MrSquaare/ssh-setup-action@v2
      with:
        host: ${{ secrets.SERVER_HOST }}
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        private-key-name: zivhsiao
    - name: Clone repo
      run:
        cd /home/cloudpanel/htdocs/clean-dev.dev-laravel.co
        git pull
        composer install
        echo "yes" | php8.1 artisan migrate
        php8.1 artisan config:cache
        php8.1 artisan view:cache
        php8.1 artisan route:cache
        php8.1 artisan config:cache






